"""Publish a demo bundle: model weights to the Hub, live demo to a Space.

Two independent steps, because they fail for different reasons and you rarely want
to redo both:

    uv run vihate publish-model --bundle <dir> --repo <user>/<model>
    uv run vihate publish-space --space <user>/<demo> --model <user>/<model>

`publish-model` makes the trained weights durable -- the thing that today
disappears with the Colab session. `publish-space` gives the demo a URL that does
not expire, which `demo.launch(share=True)` on Colab does.

Both need a Hugging Face write token: `hf auth login`, or `HF_TOKEN` in the
environment, or `--token`.
"""

import shutil
import tempfile
from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING, Final

from vihate.demo_bundle import CARD_NAME, SAMPLE_NAME, load_demo_config

if TYPE_CHECKING:
    from huggingface_hub import HfApi

PACKAGE_DIR: Final = Path(__file__).resolve().parent
# The Space runs from a staging directory with no installed package, so the modules
# it needs are shipped flat under src/ and app.py puts that on sys.path.
SPACE_MODULES: Final = ("__init__.py", "reporting.py", "demo_bundle.py", "serve_demo.py")
SPACE_SDK: Final = "gradio"
SPACE_DEFAULT_TITLE: Final = "ViHSD Vietnamese Hate-Speech Demo"
SPACE_DEFAULT_SDK_VERSION: Final = "5.50.0"
SPACE_DEFAULT_PORT: Final = 7860

SPACE_REQUIREMENTS: Final = """\
# Serving-only dependencies for the Space -- no training, no datasets.
# transformers/torch ranges match pyproject.toml; gradio is pinned because the
# generated app.py is written against the 5.x Blocks API.
torch>=2.4
transformers>=4.44,<5
huggingface-hub>=0.36
pandas>=2.2
gradio==5.50.0
"""

SPACE_APP_TEMPLATE: Final = '''"""Gradio Space entrypoint -- generated by `vihate publish-space`."""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent / "src"))

from vihate.serve_demo import ServeConfig, serve  # noqa: E402

# Baked in at publish time so the Space needs no Variables/Secrets configuration.
# Re-run `vihate publish-space --model <other/repo>` to point it somewhere else.
MODEL_REPO = "{model_repo_id}"

if __name__ == "__main__":
    serve(ServeConfig(source=MODEL_REPO, host="0.0.0.0", port={app_port}))
'''

SPACE_README_TEMPLATE: Final = """---
title: {title}
emoji: {emoji}
colorFrom: green
colorTo: red
sdk: gradio
sdk_version: {sdk_version}
app_port: {app_port}
pinned: false
license: other
short_description: Vietnamese hate-speech classifier with a calibrated HATE threshold
---

# Vietnamese Hate-Speech Detection

3-way classifier (`CLEAN` / `OFFENSIVE` / `HATE`) over real Vietnamese social-media
comments, fine-tuned on [`uitnlp/vihsd`](https://huggingface.co/datasets/uitnlp/vihsd).

Weights and the calibrated threshold come from the model repo
[`{model_repo_id}`](https://huggingface.co/{model_repo_id}); this Space only serves them.

**Content warning:** predictions quote real user-generated Vietnamese text, including
slurs. The `HATE` decision threshold is calibrated for recall, so expect false
positives in the review queue by design.
"""


class MissingSpaceSourceError(Exception):
    """Raised when the package modules a Space needs cannot be found next to publish.py."""

    def __init__(self, missing: Sequence[str]) -> None:
        """Name the missing modules and the directory they were expected in."""
        names = ", ".join(missing)
        super().__init__(f"cannot build a Space without {names} in {PACKAGE_DIR}")
        self.missing = tuple(missing)


@dataclass(frozen=True, slots=True)
class SpaceSpec:
    """How the generated Space should present and bind itself."""

    title: str = SPACE_DEFAULT_TITLE
    sdk_version: str = SPACE_DEFAULT_SDK_VERSION
    app_port: int = SPACE_DEFAULT_PORT
    private: bool = False
    token: str | None = None


def _api(token: str | None = None) -> "HfApi":
    """Return an authenticated HfApi handle, importing huggingface_hub lazily."""
    from huggingface_hub import HfApi

    return HfApi(token=token)


def push_bundle_to_hub(
    bundle_dir: Path,
    repo_id: str,
    *,
    private: bool = False,
    include_sample: bool = False,
    token: str | None = None,
) -> str:
    """Upload a demo bundle to a Hub model repo and return the repo URL.

    The ready-made sample CSV stays out by default: it is real hate-speech text from
    the ViHSD validation split, useful on your own disk, and no added exposure once
    the weights are public anyway. Pass include_sample=True to ship it regardless.
    """
    load_demo_config(bundle_dir)  # validate before uploading anything
    ignore = ["*.zip"]
    if not include_sample:
        ignore.append(SAMPLE_NAME)

    api = _api(token)
    api.create_repo(repo_id, repo_type="model", exist_ok=True, private=private)
    api.upload_folder(folder_path=str(bundle_dir), repo_id=repo_id, ignore_patterns=ignore)
    return f"https://huggingface.co/{repo_id}"


def build_space_dir(
    target_dir: Path, model_repo_id: str, spec: SpaceSpec | None = None
) -> Path:
    """Lay out the files a Gradio Space needs and return the directory."""
    resolved = spec or SpaceSpec()
    missing = [name for name in SPACE_MODULES if not (PACKAGE_DIR / name).is_file()]
    if missing:
        raise MissingSpaceSourceError(missing)

    if target_dir.exists():
        shutil.rmtree(target_dir)
    package_dir = target_dir / "src" / "vihate"
    package_dir.mkdir(parents=True)
    for name in SPACE_MODULES:
        shutil.copyfile(PACKAGE_DIR / name, package_dir / name)

    app_source = SPACE_APP_TEMPLATE.format(
        model_repo_id=model_repo_id, app_port=resolved.app_port
    )
    (target_dir / "app.py").write_text(app_source, encoding="utf-8")
    (target_dir / "requirements.txt").write_text(SPACE_REQUIREMENTS, encoding="utf-8")

    readme = SPACE_README_TEMPLATE.format(
        title=resolved.title,
        emoji="🛡️",
        sdk_version=resolved.sdk_version,
        app_port=resolved.app_port,
        model_repo_id=model_repo_id,
    )
    (target_dir / CARD_NAME).write_text(readme, encoding="utf-8")
    return target_dir


def create_demo_space(
    space_id: str, model_repo_id: str, spec: SpaceSpec | None = None
) -> str:
    """Create or update a Gradio Space that serves the published model; return its URL."""
    resolved = spec or SpaceSpec()
    api = _api(resolved.token)
    api.create_repo(
        space_id, repo_type="space", space_sdk=SPACE_SDK, exist_ok=True, private=resolved.private
    )
    with tempfile.TemporaryDirectory() as staging:
        space_dir = build_space_dir(Path(staging) / "space", model_repo_id, resolved)
        api.upload_folder(folder_path=str(space_dir), repo_id=space_id, repo_type="space")
    return f"https://huggingface.co/spaces/{space_id}"
